name: example
description: A example of mono_kit.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  mono_kit:
    path: ..
  nested:
  recase: '>=4.0.0-nullsafety.0 <5.0.0'
  simple_logger:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/