name: example
description: A example of mono_kit.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.1.0
dependencies:
  adaptive_dialog:
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutter_web_plugins:
    sdk: flutter
  go_router:
  mono_kit:
    path: ..
  nested:
  quiver:
  recase:
  simple_logger:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  go_router_builder:
  pedantic_mono:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
